CREATE TABLE IF NOT EXISTS EVENTS(
  ID UUID NOT NULL,
  EXTERNAL_ID VARCHAR(64) NOT NULL,
  ORIGIN VARCHAR(16) NOT NULL,
  TITLE VARCHAR(32) NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  POSTER VARCHAR(255) NOT NULL,
  EVENT_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  MAX_TICKETS INTEGER NOT NULL,
  SOLD_TICKETS INTEGER NOT NULL DEFAULT 0,
  CREATION_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE (EXTERNAL_ID, ORIGIN)
);

CREATE TABLE IF NOT EXISTS TICKETS(
  ID UUID NOT NULL,
  EVENT_ID UUID NOT NULL,
  PARTICIPANT_ID UUID NOT NULL,
  CREATION_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE (PARTICIPANT_ID, EVENT_ID),
  FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(ID)
);
